[workspace]
members = ["crates/syncopate", "crates/benchmark"]
resolver = "2"

[workspace.package]
version = "0.0.1"
authors = ["Zibi Braniecki <zibi@braniecki.net>"]
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/zbraniecki/syncopate"

[profile.release]
opt-level = 3
lto = true
